version: "3.9"

services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=zabawkowe
  web:
    build: .
    command: python3 app.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=zabawkowe
    depends_on:
      - db
    restart: on-failure
